# Generated by Django 4.2.1 on 2023-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('role_description', models.TextField(max_length=1000)),
                ('time_working_for_company', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
