# Generated by Django 4.2.1 on 2023-08-27 21:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='about_me_blurb',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
