# Generated by Django 4.2.1 on 2023-08-05 15:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
