# Generated by Django 4.2.1 on 2023-08-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_aboutme_about_me_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='download_cv',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
