# Generated by Django 4.2.1 on 2023-08-21 14:04

# import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_aboutme_options_alter_certificates_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mywork',
            options={'verbose_name_plural': 'My Work'},
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_body',
            field=models.TextField(max_length=5000, blank=False, null=False, default=True),
        ),
    ]
