# Generated by Django 4.2.1 on 2023-08-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_aboutme_download_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='download_cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
