# Generated by Django 4.2.1 on 2023-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('certificate_aquired_through', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('certificate_description', models.TextField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
    ]
