# Generated by Django 4.2.1 on 2023-08-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_post_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blockquote',
        ),
    ]
