# Generated by Django 4.2.1 on 2023-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='certificate_completion_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
