# Generated by Django 4.2.1 on 2023-08-05 15:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_post_blockquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
