# Generated by Django 4.2.1 on 2023-08-21 14:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_post_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_body',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
