# Generated by Django 4.2.1 on 2023-08-26 13:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_post_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_body',
            field=ckeditor.fields.RichTextField(default='', max_length=5000),
        ),
    ]
