# Generated by Django 4.2.1 on 2023-07-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='blog_body',
        ),
    ]
