# Generated by Django 4.2.1 on 2023-07-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_post_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_list_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
